# stages:
#   - test
#   - build
# test project:
#   stage: test
#   image: node:15
#   script:
#   - npm install
#   - npm run build
# build project:
#   stage: build
#   image: node:15
#   script:
#   - npm install
#   - npm run build

# Define stages for the pipeline
stages:
  - build
  - deploy

# Job to build the React project
build:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - npm install --force
    - npm run build
  artifacts:
    paths:
      - build

# Job to deploy the built project to GitLab Pages
deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r build/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
  - banaja
  
